# -*- coding: utf-8 -*-

import scrapy


class HkjcHorseItem(scrapy.Item):
    racenumber = scrapy.Field()
    raceindex = scrapy.Field()
    racename = scrapy.Field()
    horsenumber = scrapy.Field()
    horsename = scrapy.Field()
    horsecode = scrapy.Field()
    timelist = scrapy.Field()
    sirename = scrapy.Field()
    racedate = scrapy.Field()
    place = scrapy.Field()
    final_sec_time = scrapy.Field()
    raceclass = scrapy.Field()
    racedistance = scrapy.Field()
    racegoing = scrapy.Field()
    racetrack = scrapy.Field()
    horsecodelist = scrapy.Field()
    racingincidentreport = scrapy.Field()
    jockeyname = scrapy.Field()
    jockeycode = scrapy.Field()
    trainername = scrapy.Field()
    trainercode = scrapy.Field()
    actualwt = scrapy.Field()
    declarhorsewt = scrapy.Field()
    jockey2horsewt = scrapy.Field()
    draw = scrapy.Field()
    lbw = scrapy.Field()
    runningposition = scrapy.Field()
    finishtime = scrapy.Field()
    winoddsrank = scrapy.Field()
    marginsbehindleader = scrapy.Field()
    ownername = scrapy.Field()
    dam = scrapy.Field()
    damsire = scrapy.Field()
